### PR TITLE
Don't prompt about dotnet deploy config if using remote build

### LINKED ISSUE #1242: Setting SCM_DO_BUILD_DURING_DEPLOYMENT=true does not trigger a build when deployed
I would expect a build to be kicked off on the server when the flag `SCM_DO_BUILD_DURING_DEPLOYMENT=true` is set but instead a `publish` happens locally and it's contents are zipped and deployed to server.

Repro steps:
1. Create a new .NET Core 3.0 app using `dotnet new empty` and add a `.deployment` file in it with the following content:
```
[config]
SCM_DO_BUILD_DURING_DEPLOYMENT=true
```
2. Now click `Deploy Web App....`

**Expected**: Build should be kicked off on the server
**Actual**: Build and publish is done locally and content of publish folder is deployed instead.

**Log output:**
```
4:58:43 AM: Creating resource group "kichallaUserVoiceApp" in location "westus2"...
4:58:44 AM: Successfully created resource group "kichallaUserVoiceApp".
4:58:44 AM: Ensuring App Service plan "kichallaUserVoiceApp" exists...
4:58:44 AM: Creating App Service plan "kichallaUserVoiceApp"...
4:58:50 AM: Successfully created App Service plan "kichallaUserVoiceApp".
4:58:50 AM: Creating new web app "kichallaUserVoiceApp"...
4:59:08 AM: Created new web app "kichallaUserVoiceApp": https://kichallauservoiceapp.azurewebsites.net
4:59:30 AM: Enabling Logging for "kichallaUserVoiceApp"...
4:59:31 AM: Stopping "kichallaUserVoiceApp"...
4:59:31 AM: "kichallaUserVoiceApp" has been stopped. App Service plan charges still apply.
4:59:31 AM: Starting "kichallaUserVoiceApp"...
4:59:32 AM: "kichallaUserVoiceApp" has been started.
4:59:32 AM: Enabled Logging for "kichallaUserVoiceApp".
5:01:52 AM kichallaUserVoiceApp: Creating zip package...
5:01:52 AM kichallaUserVoiceApp: Starting deployment...
5:02:02 AM kichallaUserVoiceApp: Updating submodules.
5:02:02 AM kichallaUserVoiceApp: Preparing deployment for commit id 'e98c1a9b06'.
5:02:02 AM kichallaUserVoiceApp: Generating deployment script.
5:02:02 AM kichallaUserVoiceApp: Using the following command to generate deployment script: 'azure site deploymentscript -y --no-dot-deployment -r "/tmp/zipdeploy/extracted" -o "/home/site/deployments/tools" --basic --sitePath "/tmp/zipdeploy/extracted"'.
5:02:03 AM kichallaUserVoiceApp: Generating deployment script for Web Site
5:02:03 AM kichallaUserVoiceApp: Generated deployment script files
5:02:04 AM kichallaUserVoiceApp: Running deployment command...
5:02:04 AM kichallaUserVoiceApp: Command: "/home/site/deployments/tools/deploy.sh"
5:02:04 AM kichallaUserVoiceApp: Handling Basic Web Site deployment.
5:02:04 AM kichallaUserVoiceApp: Kudu sync from: '/tmp/zipdeploy/extracted' to: '/home/site/wwwroot'
5:02:04 AM kichallaUserVoiceApp: Copying file: 'appsettings.Development.json'
5:02:04 AM kichallaUserVoiceApp: Copying file: 'appsettings.json'
5:02:04 AM kichallaUserVoiceApp: Copying file: 'uservoiceapp.deps.json'
5:02:04 AM kichallaUserVoiceApp: Copying file: 'uservoiceapp.dll'
5:02:04 AM kichallaUserVoiceApp: Copying file: 'uservoiceapp.exe'
5:02:04 AM kichallaUserVoiceApp: Copying file: 'uservoiceapp.pdb'
5:02:04 AM kichallaUserVoiceApp: Copying file: 'uservoiceapp.runtimeconfig.json'
5:02:04 AM kichallaUserVoiceApp: Copying file: 'web.config'
5:02:04 AM kichallaUserVoiceApp: Deleting file: 'hostingstart.html'
5:02:04 AM kichallaUserVoiceApp: Finished successfully.
5:02:04 AM kichallaUserVoiceApp: Running post deployment command(s)...
5:02:04 AM kichallaUserVoiceApp: Deployment successful.
5:02:05 AM kichallaUserVoiceApp: App container will begin restart within 10 seconds.
5:02:13 AM kichallaUserVoiceApp: Waiting for long running command to finish...
5:02:13 AM: Deployment to "kichallaUserVoiceApp" completed.
```

cc @fiveisprime @gpcastro

### PR DESCRIPTION
**Pull request by EricJizbaMSFT**
Fixes #1242

### CODE REVIEW

**Comment by EricJizbaMSFT** [comment]
Also worth noting, I tried remote build for the scenario described in the bug (.NET Core web app) and it worked just fine for me.

File: src/commands/deploy/setPreDeployTaskForDotnet.ts [hunk 1]
```diff
@@ -33,6 +33,16 @@ export async function setPreDeployTaskForDotnet(context: IDeployContext): Promis
         return;
     }
 
+    // if the user has scmDoBuild configured in a ".deployment" file - assume they've already configured their project's deploy settings
+    const deploymentFilePath: string = path.join(context.effectiveDeployFsPath, constants.deploymentFileName);
```
Comment (nturinski) [inline src/commands/deploy/setPreDeployTaskForDotnet.ts:37]: I'm of the opinion that if a user has a deployment file at all, there are custom build scripts that they could have and we may want to avoid setting any preDeployTasks/deploySubpath since it could break those users not just if they have scmDoBuild set.

Comment (EricJizbaMSFT) [reply src/commands/deploy/setPreDeployTaskForDotnet.ts:37]: I can jive with that
