### PR TITLE
Reorder loadMoreChildrenImpl calls

### LINKED ISSUE #1600: Sign-in/Create account tree items never load if a trial app exists
### Repro steps:

1. Sign out of Azure
2. Import trial app
3. Reload window

### Expected behavior: 
Sign-in and Create account tree items load, along with the imported trial app.

### Actual behavior:
The `Loading...` node stays there forever.

image

#### Note: Refreshing the tree using the refresh button makes everything load properly.

Possibly related to https://github.com/microsoft/vscode-azuretools/issues/741

### PR DESCRIPTION
**Pull request by alexweininger**
Fixes #1600 for me. However, I'd like some more testing because it's such a weird fix.

This fix works because I moved the `await super.loadMoreChildrenImpl(clearCache, context)` call so that's it's after all other async calls in the function.

### CODE REVIEW

**Comment by nturinski** [comment]
I think we should investigate the root cause more.  We're gonna run out of places to move that line of code 😬

File: src/explorer/AzureAccountTreeItem.ts [hunk 1]
```diff
@@ -28,9 +28,11 @@ export class AzureAccountTreeItem extends AzureAccountTreeItemBase {
 
     public async loadMoreChildrenImpl(clearCache: boolean, context: IActionContext): Promise<AzExtTreeItem[]> {
         const ti: AzExtTreeItem | undefined = this.trialAppNode ?? await this.loadTrialAppNode();
-        const children: AzExtTreeItem[] = await super.loadMoreChildrenImpl(clearCache, context);
         await this.setContext(ti);
 
+        // Must be called after all other async calls to prevent getting stuck on the "Loading..." tree item.
```
Comment (EricJizbaMSFT) [inline src/explorer/AzureAccountTreeItem.ts:33]: Lol a bit overconfident IMO. I would add a comment like this:

```
// Putting this after all other async calls to hopefully fix https://github.com/microsoft/vscode-azureappservice/issues/1600
```
