### PR TITLE
openInPortal

### LINKED ISSUE #1602: An error occurs when executing "Open in Portal" action for "Application Settings" node
**OS:** Win 10/Mac
**Build Version:** 20200616.2

**Repro Steps:**
1. Expand one web app.
2. Right click the "Application Settings" node and select "Open in Portal".

**Expect:**
Open in portal successfully without any error.

**Actual:**
An error occurs.
image

### PR DESCRIPTION
**Pull request by alexweininger**
Depends on https://github.com/microsoft/vscode-azuretools/pull/752

Fixes #1602

### CODE REVIEW

File: src/commands/openInPortal.ts [hunk 1]
```diff
@@ -4,30 +4,29 @@
...
-import { IActionContext, openInPortal as uiOpenInPortal } from "vscode-azureextensionui";
+import { AzExtParentTreeItem, IActionContext, openInPortal as uiOpenInPortal } from "vscode-azureextensionui";
 import { DeploymentSlotsTreeItem } from "../explorer/DeploymentSlotsTreeItem";
-import { SiteTreeItem } from "../explorer/SiteTreeItem";
 import { WebAppTreeItem } from "../explorer/WebAppTreeItem";
 import { ext } from "../extensionVariables";
 import { nonNullProp } from "../utils/nonNull";
 
-export async function openInPortal(context: IActionContext, node?: SiteTreeItem): Promise<void> {
+export async function openInPortal(context: IActionContext, node?: AzExtParentTreeItem): Promise<void> {
```
Comment (EricJizbaMSFT) [inline src/commands/openInPortal.ts:13]: Doesn't need to be a parent does it?

Comment (alexweininger) [reply src/commands/openInPortal.ts]: Changed to `AzExtTreeItem`
