### PR TITLE
Better handle expired Trial apps

### LINKED ISSUE #1645: The state of Trial App will change to "Invalid" after it expired about four mins
**OS:** Win10
**Build Version:** 20200701.1

**Repro Steps:**
1. Create a new Trial App and wait for it to expire.
2. Refresh the Trial App after several mins.

**Expect:**
The state of the Trial App has always been expired.

**Actual:**
The state of Trial App from Expired change to Invalid.
image

### PR DESCRIPTION
**Pull request by alexweininger**
Some edge cases that I had to handle here:

1. Importing an expired trial app
    a. If we are still able to get the trial app metadata (the timeLeft property is undefined in this case).
    b. If the request to get metadata returns an error.
2. Reloading VS Code with an expired trial app. This is why I had to add additional information to the context.globalState

Fixes #1645

### CODE REVIEW

File: src/commands/trialApp/importTrialApp.ts [hunk 1]
```diff
@@ -15,7 +16,22 @@ export async function importTrialApp(_context: IActionContext, loginSession: str
     await window.withProgress({ location: ProgressLocation.Notification, cancellable: false }, async p => {
         p.report({ message: localize('importingTrialApp', 'Importing trial app...') });
         ext.azureAccountTreeItem.trialAppNode = await TrialAppTreeItem.createTrialAppTreeItem(ext.azureAccountTreeItem, loginSession);
-        ext.context.globalState.update(TrialAppLoginSession, loginSession);
+        const trialAppNode = ext.azureAccountTreeItem.trialAppNode;
+
+        if (trialAppNode.client.metadata.timeLeft === undefined) {
```
Comment (nturinski) [inline src/commands/trialApp/importTrialApp.ts:21]: Please leave a comment explaining why we need this check

File: src/commands/trialApp/importTrialApp.ts [hunk 2]
```diff
@@ -15,7 +16,22 @@ export async function importTrialApp(_context: IActionContext, loginSession: str
...
+            throw new Error(localize('trialAppExpired', 'Trial app is expired. Could not import.'));
+        }
+
+        const expirationDate: Date = new Date();
```
Comment (nturinski) [inline src/commands/trialApp/importTrialApp.ts:25]: Use Date.now()  which returns the current time in ms.  Then just add the timeLeft * 1000

File: src/explorer/AzureAccountTreeItem.ts [hunk 3]
```diff
@@ -67,16 +69,19 @@ export class AzureAccountTreeItem extends AzureAccountTreeItemBase {
...
             this.trialAppNode = undefined;
             return undefined;
         }
 
         const ti: AzExtTreeItem[] = await this.createTreeItemsWithErrorHandling(
-            [loginSession],
+            [trialAppContext.loginSession],
             'trialAppInvalid',
             async (source: string): Promise<AzExtTreeItem> => {
+                if (new Date(trialAppContext.expirationDate) < new Date()) {
```
Comment (nturinski) [inline src/explorer/AzureAccountTreeItem.ts:82]: I'd use a ternary just so it's clear there's 2 different types of trees that we can return here
