### PR TITLE
Fix #120

### LINKED ISSUE #120: Wrong order of "Disconnect" and "Connect" in log stream output
Steps to repro:

1. Connect to log stream.
2. Immediately connect to log stream again.

The 2nd connect command will disconnect the first connection and start a new one. However, in the output "Connect" is printed first, then "Disconnect".

### PR DESCRIPTION
**Pull request by whiskeyjay**
Fix #120

### CODE REVIEW

File: src/explorer/siteNodeBase.ts [hunk 1]
```diff
@@ -74,9 +74,9 @@ export class SiteNodeBase extends NodeBase {
 
         if (util.isSiteDeploymentSlot(this.site)) {
             const slotName = util.extractDeploymentSlotName(this.site);
-            await this.webSiteClient.webApps.stopSlot(rgName, siteName, slotName);
+            await this.webSiteClient.webApps.stopSlotWithHttpOperationResponse(rgName, siteName, slotName);
```
Comment (EricJizbaMSFT) [inline src/explorer/siteNodeBase.ts]: Discussed offline and I don't think 'stopSlotWithHttpOperationResponse' is necessary (but also wouldn't hurt)
