### PR TITLE
Output logs when opening and uploading files

### LINKED ISSUE #1610: There is no output log and notification when updating the file
**OS:** Mac
**Build Version:** 20200618.1
**.NET Core:** 2.1

**Repro Steps:**

1. Expand one web app --> Files --> Open one file.
2. Make some change for this file and save it.
3. Check the output log.

**Expect:**
There is output log and notification.

**Actual:**
There is no output log and notification.

### PR DESCRIPTION
**Pull request by alexweininger**
Fixes #1610

### CODE REVIEW

File: src/AppServiceFileSystem.ts [hunk 1]
```diff
@@ -58,4 +60,9 @@ export class AppServiceFileSystem extends AzExtTreeFileSystem<FileTreeItem> {
         this._etags.set(node.fullId, etag);
         await node.refresh();
     }
+
+    public appendLineToOutput(value: string, options?: { resourceName?: string, date?: Date }): void {
+        ext.outputChannel.appendLog(value, options);
+        ext.outputChannel.show(true);
```
Comment (EricJizbaMSFT) [inline src/AppServiceFileSystem.ts:66]: We [generally avoid](https://github.com/microsoft/vscode-azureappservice/issues/455) showing the output channel because it can get annoying

File: src/AppServiceFileSystem.ts [hunk 2]
```diff
@@ -58,4 +60,8 @@ export class AppServiceFileSystem extends AzExtTreeFileSystem<FileTreeItem> {
         this._etags.set(node.fullId, etag);
         await node.refresh();
     }
+
+    public appendLineToOutput(value: string, options?: { resourceName?: string, date?: Date }): void {
+        ext.outputChannel.appendLog(value, options);
```
Comment (EricJizbaMSFT) [inline src/AppServiceFileSystem.ts:65]: Remove `appendLineToOutput` because it doesn't do anything and just use `ext.outputChannel.appendLog` directly
